### ISSUE TITLE
document the pdffigures2 method

### ISSUE THREAD

**Issue by DevinBayly** [VisSieve/main#17]

**Comment by DevinBayly** [comment]
this issue is a precursor to the wiki page (which I will write later) information for this method

steps
* retrieve and convert the pdffigures2 container to singularity on your hpc `singularity build pdffigures2.sif docker://ghcr.io/devinbayly/pdffigures2`
* to run `singularity shell pdffigures2.sif`
* in order to use the `sbt` program which was installed we need to source this installed file `source "/root/.sdkman/bin/sdkman-init.sh"`
* then we need to access the cloned repo `git clone https://github.com/allenai/pdffigures2.git`
* go inside the folder `cd pdffigures2`
* then run the bulk pdf figure extractor 
```
sbt "runMain org.allenai.pdffigures2.FigureExtractorBatchCli /path/to/pdf_directory/ -s stat_file.json -m /figure/image/output/prefix -d /figure/data/output/prefix"
```
in the above command the `/path/to/pdf_directory` is a folder with pdfs inside it, the `/figure/image/output/prefix` is whatever gets added to the `fig1-1.png` figures that follow a system like `fig{page}-{number}` for their identification. 

the `/figure/data/output/prefix` is the prefix added to the json files that tell us about the figure or table that was extracted from the pdf

**Comment by DevinBayly** [comment]
@carolinarr this will be useful information for tomorrows meeting in case you want to run extraction on other pdfs not from princeton 2022

**Comment by carolinarr** [comment]
Hey Devin, thanks for this protocol! I was able to do the following:

- retrieve and convert the pdffigures2 container to singularity on your hpc `singularity build pdffigures2.sif docker://ghcr.io/devinbayly/pdffigures2`
- to run `singularity shell pdffigures2.sif`

but got stuck here

- in order to use the sbt program which was installed we need to source this installed file `source "/root/.sdkman/bin/sdkman-init.sh"`

where I kept getting a "Permission denied" output:

```
Apptainer> source "/root/.sdkman/bin/sdkman-init.sh"
bash: /root/.sdkman/bin/sdkman-init.sh: Permission denied
```

**Comment by DevinBayly** [comment]
shoot! Let me try that part again from scratch. Thanks for digging into all this

________________________________
From: Carolina Roe-Raymond ***@***.***>
Sent: Tuesday, July 2, 2024 8:43 AM
To: VisSieve/main ***@***.***>
Cc: Bayly, Devin Richard - (baylyd) ***@***.***>; Author ***@***.***>
Subject: [EXT] Re: [VisSieve/main] document the pdffigures2 method (Issue #17)


External Email

________________________________
Hey Devin, thanks for this protocol! I was able to do the following:

  *   retrieve and convert the pdffigures2 container to singularity on your hpc singularity build pdffigures2.sif docker://ghcr.io/devinbayly/pdffigures2<docker://ghcr.io/devinbayly/pdffigures2>
  *   to run singularity shell pdffigures2.sif

but got stuck here

  *   in order to use the sbt program which was installed we need to source this installed file source "/root/.sdkman/bin/sdkman-init.sh"

where I kept getting a "Permission denied" output:

Apptainer> source "/root/.sdkman/bin/sdkman-init.sh"
bash: /root/.sdkman/bin/sdkman-init.sh: Permission denied

**Comment by DevinBayly** [comment]
I think there's two things we can try, one instead of using `singularity shell pdffigures2.sif` try it with a `-f` after the shell part 
`singularity shell -f pdffigures2.sif` , this will start the container with a fake root user so you can access that `/root` folder

The other thing is perhaps I can rebuild and install sdkman in a diffferent folder that normal users have access to. Just let me know if you can't use the `-f` option and we can try the other thing

**Comment by carolinarr** [comment]
Darn, I tried but got this result:

```
[csimao@della-vis1 vis-sieve]$ singularity shell -f pdffigures2.sif
INFO:    User not listed in /etc/subuid, trying root-mapped namespace
INFO:    No user namespaces available
INFO:    The fakeroot command by itself is only useful with sandbox images
INFO:     which can be built with 'apptainer build --sandbox'
FATAL:   --fakeroot used without sandbox image or user namespaces
```

If it's easy to try to rebuild let's try that. If it's complicated or you don't have the time, I'm happy to try to see if I can install sbt and run pdffigures2 on my side.

**Comment by DevinBayly** [comment]
Ok, I added a single line to the container building process that made the `/root/.sdkman` folder recursively available, I have tried building and running a container with the above instructions and the source command works now. 

Would you give it a try when you have a moment @carolinarr ?

**Comment by carolinarr** [comment]
Hey there, it was a no go with the original code instructions, but I had a little progress when I built the image using --sandbox (as in, I got more than a "Permission denied" error message):

```
[csimao@della-vis1 ~]$ singularity build --sandbox pdffigures2.sif docker://ghcr.io/devinbayly/pdffigures2
Build target 'pdffigures2.sif' already exists and will be deleted during the build process. Do you want to continue? [N/y] y
INFO:    Starting build...
Getting image source signatures
Copying blob 2b3981cac065 skipped: already exists  
Copying blob ac7498a4c6a9 skipped: already exists  
Copying blob ac519235dbf5 skipped: already exists  
Copying blob 4f4fb700ef54 skipped: already exists  
Copying blob 6d40753bef58 skipped: already exists  
Copying blob 6eb6da385ca1 skipped: already exists  
Copying blob 36d02117deef skipped: already exists  
Copying blob a5909b8ab02e skipped: already exists  
Copying config fa977bbfa5 done  
Writing manifest to image destination
Storing signatures
2024/07/09 14:43:09  info unpack layer: sha256:2b3981cac065674916a0b4e8d1b5d7eb49d9863a79ec47ba37336c70496ac8ab
2024/07/09 14:43:09  warn xattr{etc/gshadow} ignoring ENOTSUP on setxattr "user.rootlesscontainers"
2024/07/09 14:43:09  warn xattr{/home/csimao/build-temp-4011557216/rootfs/etc/gshadow} destination filesystem does not support xattrs, further warnings will be suppressed
2024/07/09 14:43:12  info unpack layer: sha256:6eb6da385ca16d87706bbc4c4d69edea56697546308e3b11bdad1f6f238eee94
2024/07/09 14:43:12  warn xattr{var/lib/apt/lists/auxfiles} ignoring ENOTSUP on setxattr "user.rootlesscontainers"
2024/07/09 14:43:12  warn xattr{/home/csimao/build-temp-4011557216/rootfs/var/lib/apt/lists/auxfiles} destination filesystem does not support xattrs, further warnings will be suppressed
2024/07/09 14:43:12  info unpack layer: sha256:6d40753bef58ea5a0c6cd9aaa5ca8c8b14bb6ff7f663c44ebda7ac465a4a55f6
2024/07/09 14:43:12  warn xattr{etc/gshadow} ignoring ENOTSUP on setxattr "user.rootlesscontainers"
2024/07/09 14:43:12  warn xattr{/home/csimao/build-temp-4011557216/rootfs/etc/gshadow} destination filesystem does not support xattrs, further warnings will be suppressed
2024/07/09 14:43:15  info unpack layer: sha256:ac7498a4c6a94820f3d7144917fb8b9a637e68818f41055f4635483a1b957e3b
2024/07/09 14:43:15  info unpack layer: sha256:4f4fb700ef54461cfa02571ae0db9a0dc1e0cdb5577484a6d75e68dc38e8acc1
2024/07/09 14:43:15  info unpack layer: sha256:ac519235dbf5f1bbcb5d6fcc48c1511a184305baf92548ab7baa1df825345b52
2024/07/09 14:43:20  info unpack layer: sha256:36d02117deef09619dd3bb889f48b1fe1243cd5ee3890096c8c219c2efda2d71
2024/07/09 14:43:24  info unpack layer: sha256:a5909b8ab02e6b1d797768b84e90ae6b5ef1ce16060cf22c8dc424ae4ffb4300
INFO:    Creating sandbox directory...
INFO:    Build complete: pdffigures2.sif
[csimao@della-vis1 ~]$ singularity shell -f pdffigures2.sif
INFO:    User not listed in /etc/subuid, trying root-mapped namespace
INFO:    No user namespaces available, using only the fakeroot command
Apptainer> source "/root/.sdkman/bin/sdkman-init.sh"
cat: /home/csimao/.sdkman/var/platform: No such file or directory
find: '/home/csimao/.sdkman/src': No such file or directory
find: '/home/csimao/.sdkman/ext': No such file or directory
touch: cannot touch '/home/csimao/.sdkman/var/delay_upgrade': No such file or directory
bash: /home/csimao/.sdkman/var/candidates: No such file or directory
bash: __sdkman_echo_debug: command not found
Apptainer> pwd
/home/csimao
```

But now the above shows 'no such file or directory' error messages. For context, the above was done on one our clusters.

Next, I tried to just use docker on my local machine (for the first time, so not sure if the below all checks out), but I did get farther...

```
% docker pull ghcr.io/devinbayly/pdffigures2
% docker run -it ghcr.io/devinbayly/pdffigures2
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
root@95fa49c1fb3b:/opt# source "/root/.sdkman/bin/sdkman-init.sh"
root@95fa49c1fb3b:/opt# git clone https://github.com/allenai/pdffigures2.git
root@95fa49c1fb3b:/opt# ls
pdffigures2
root@95fa49c1fb3b:/opt# cd pdffigures2/
root@95fa49c1fb3b:/opt/pdffigures2# ls
LICENSE.txt  README.md  build.sbt  evaluation  project  src
root@95fa49c1fb3b:/opt/pdffigures2# sbt "runMain org.allenai.pdffigures2.FigureExtractorBatchCli /Users/csimao/onedrive_princeton/projects/personal_projs/vis_sieve_princeton/vis-sieve-carolina/python/testing/ -s stat_file.json -m fig{page}-{number} -d /fig{page}-{number}"
```
I was a little confused about how to format the /figure/image-or-data/output/prefixes should look, but regardless, the result of the above was:

```
[info] [launcher] getting org.scala-sbt sbt 1.7.1  (this may take some time)...
[info] [launcher] getting Scala 2.12.16 (for sbt)...
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007ffffe9e736c, pid=50, tid=0x00007ffffd7ff6c0
#
# JRE version: OpenJDK Runtime Environment (8.0_412-b08) (build 1.8.0_412-b08)
# Java VM: OpenJDK 64-Bit Server VM (25.412-b08 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# V  [libjvm.so+0x9e736c]  StealTask::do_it(GCTaskManager*, unsigned int)+0x47c
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /opt/pdffigures2/hs_err_pid50.log
#
# If you would like to submit a bug report, please visit:
#   https://github.com/adoptium/adoptium-support/issues
#
Aborted
```
I've run out of time to troubleshoot today, but hopefully we can discuss what to try next in our upcoming meeting.

**Comment by DevinBayly** [comment]
suggested fix is to add 
```
cd ~
ln -s /root/.sdkman 
# same as typing ln -s /root/.sdkman .sdkman, but less redundant

# run either of these
source "/root/.sdkman/bin/sdkman-init.sh"
# or this, but I'll comment this out since we haven't tested
#source "/root/.sdkman/bin/sdkman-init.sh"
```

**Comment by DevinBayly** [comment]
for context, the command that I ran to kick off pdffigures2 with outputting the figures was
```
sbt "runMain org.allenai.pdffigures2.FigureExtractorBatchCli /home/u4/baylyd/Desktop/xdisk_me/vis_sieve/vis-sieve/pdf_grabbing/pdf_symlinks -s stat_file.json -m /home/u4/baylyd/Desktop/xdisk_me/vis_sieve/vis-sieve/pdf_grabbing/pdf_symlinks/pdf_fig -d /home/u4/baylyd/Desktop/xdisk_me/vis_sieve/vis-sieve/pdf_grabbing/pdf_symlinks/pdf_data"
```
